### ISSUE TITLE
Update DB Library

### ISSUE THREAD

**Issue by mitchwadair** [mitchwadair/mthebot#58]
Currently MtheBot uses the `mysql` nodejs library but there is a newer, better, library: [mysql2](https://www.npmjs.com/package/mysql2)

**Comment by MadyDixit** [comment]
Hi @mitchwadair ,

I have resolved the issue. Upgrade the DB version. Please check the pull request.

**Comment by mitchwadair** [comment]
Closed by #59

**Comment by mitchwadair** [comment]
Reopening, needs some more work. See [this issue](https://github.com/sidorares/node-mysql2/issues/939)

**Comment by MadyDixit** [comment]
Hi @mitchwadair, I go through your dbservice.js  as well as the issue you tag in the last comment. I have followed all the threads and found some conclusions.
1. It's working with a single connection, not with the pool. If we use promise it can be easily avoidable. This issue or error came in createconnection when we try to close the connection and the service remain in the process.  
2. We do not call any connection closing code in dbservice. So it is safer. And promise for any querying result. So we can proceed with existing code.
If you find something new, please let me know.

**Comment by mitchwadair** [comment]
The code does work fine for the most part.  The problem is when the connection gets timed out.  To give some context, here is a snippet of logs I received in prod:
```
Jan 28 01:14:04 ip-████████ web: January 28, 2022 01:14:04:509 - TESjs - Received notification for type channel.follow
Jan 28 01:14:04 ip-████████ web: Fri, 28 Jan 2022 01:14:04 GMT ** BOT: ERROR ON CHANNEL ████: Error: Can't add new command when connection is in closed state
Jan 28 01:18:43 ip-████████ web: January 28, 2022 01:18:43:733 - TESjs - Received notification for type channel.follow
Jan 28 01:18:44 ip-████████ web: Fri, 28 Jan 2022 01:18:44 GMT ** BOT: ERROR ON CHANNEL ████: Error: Can't add new command when connection is in closed state
Jan 28 01:19:10 ip-████████ web: Fri, 28 Jan 2022 01:19:10 GMT ** BOT: ERROR ON CHANNEL ████: Error: Can't add new command when connection is in closed state
Jan 28 01:37:01 ip-████████ web: Fri, 28 Jan 2022 01:37:01 GMT ** BOT: ERROR ON CHANNEL ████: Error: Can't add new command when connection is in closed state
```
You can see that the error popped up.  The reason for this is because the userbase is so small that the connection was not being used for 8+ hours and got timed out (which I guess is a difference between `mysql` and `mysql2`).  Due to this, attempts to fetch channel information failed both when interacting with chat as well as on the website, and that required a restart of the EC2 environment to get it working again.
