### ISSUE TITLE
Make All Config Items Environment Variables (or JSON)

### ISSUE THREAD

**Issue by mitchwadair** [mitchwadair/mthebot#61]
There are a few places where things are still hard-coded into MtheBot.  Most notably the TES base URL off the top of my head.  It should be ensured that everything like that should be an env var or have some kind of configuration file to source from.  The config file route may have some positive advantages but could be difficult to set up for some production instances

**Comment by MadyDixit** [comment]
Hi @mitchwadair , I have create the common configuration folder which contain all URLs. Have look.
